Add android test app
ably/ably-dotnet pull request #1026
Opened 2021-11-12 17:28 UTC by marto83

Include an Xamarin Forms App (the Android part) + a notification pusher. There is probably a few code styles issues so `Tom` feel free to flag them until I get the apps cleaned up :)

2021-11-12 18:34 UTC, sacOO7 approved these changes

2021-11-12 18:36 UTC, sacOO7 commented
@marto83 you can check why some of those tests are failing. (Also, just an idea, we can include SS of working app under android test app README )

2021-11-12 18:39 UTC, marto83 commented
Good idea about the screen shots. I'm getting the iOS app working as well and will do a separate readme for the push notifications. 

It's weird because it's not a test that I have touch with this PR but I can definitely make the test more robust. Thanks @sacOO7

2021-11-15 10:26 UTC, tomkirbygreen requested changes

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +                alert += (aps[new NSString("alert")] as NSString).ToString();
Missing `{` ... `}`.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +            //show alert
One space following `//` please.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +            var alertWindow = new UIWindow(UIScreen.MainScreen.Bounds);
Lines 106 - 114 use object-initialiser syntax.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/AblySettings.cs
> +            get => Preferences.Get("ABLY_CLIENT_ID", string.Empty, "Ably_Device");
Duplicated constant string.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/AblySettings.cs
> +            get => Preferences.Get("ABLY_AUTH_KEY", string.Empty, "Ably_Device");
Duplicated constant string.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/ViewModels/BaseViewModel.cs
> +        /// Triggers PropertyChanged event for a cert.
'cert' is an abbreviation for certificate?

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/ViewModels/StateViewModel.cs
> +            model.StateMachine.CurrentState = GetStateMachineProperty("ABLY_PUSH_CURRENT_STATE");
Use object-initialiser syntax please.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/ViewModels/SubscribeViewModel.cs
> +            // pushRealtime.OnActivationSta teMachineChangeState((current, next) =>
Did you mean to leave this here?

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/AppLogger.cs
> +                return;
Missing `{` ... `}`.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/AppLogger.cs
> +        private int maxMessages = 1000;
Should be `private const int MaxMessages = 1000`.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Program.cs
> +            // Channel
To what do this next two comment lines refer?

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Program.cs
> +            var messageNameLabel = new Label("Name:") { X = 1, Y = 1, Width = 10};
One space preceding the closing `}` please, here and elsewhere.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Program.cs
> +    ""push"": {
White space issue?

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Program.cs
> +    ""push"": {
White-space issue?

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Program.cs
> +        private static string ablyKey = "";
Use `string.Empty` rather than `""`.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Program.cs
> +            if (File.Exists("key.secret"))
Duplicated constant string.

2021-11-15 10:26 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Program.cs
> +                    new MenuItem("_Quit", "", Quit)
Use `string.empty`, as you did on lines `402`, rather than `""`.

2021-11-15 10:26 UTC, tomkirbygreen commented on src/IO.Ably.Push.Android/AndroidMobileDevice.cs
> +                var idiom = DeviceInfo.Idiom;
Lines 113 to 138, can this not be a `switch` expression?

2021-11-15 13:06 UTC, marto83 commented on src/IO.Ably.Push.Android/AndroidMobileDevice.cs
> +                var idiom = DeviceInfo.Idiom;
Unfortunately, you can't use a switch. I did try originally. The values are not constants and are objects which can't be used in a switch statement. We could probably use the pattern matching switch when we upgrade to c# 9

2021-11-15 13:06 UTC, marto83 commented on examples/NotificationsPublisher/Program.cs
> +                    new MenuItem("_Quit", "", Quit)
Done

2021-11-15 13:06 UTC, marto83 commented on examples/NotificationsPublisher/Program.cs
> +            if (File.Exists("key.secret"))
Created a constant for the filename :)

2021-11-15 13:06 UTC, marto83 commented on examples/NotificationsPublisher/Program.cs
> +        private static string ablyKey = "";
done

2021-11-15 13:06 UTC, marto83 commented on examples/NotificationsPublisher/Program.cs
> +    ""push"": {
You have to keep the whitespace as it is so it displays nicely in the UI

2021-11-15 13:06 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +            if (string.IsNullOrWhiteSpace(savedClientId) == false)
Done

2021-11-15 13:07 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +            options.Key = "GJvITg.Jnks6w:IUoxrgaHjIw5LHQG"; // TODO: Remove and delete Martin's app.
Removed and added a comment with what should be used. I've also removed the app from my account so the key is no longer valid.

2021-11-15 13:07 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/MyFirebaseMessaging.cs
> +            Intent intent = new Intent(this, typeof(MainActivity));
Done :)

2021-11-15 13:07 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/MyFirebaseMessaging.cs
> +                Title = title ?? "",
Done

2021-11-22 10:35 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/MyFirebaseMessaging.cs
> +        private string notificationChannelId = "AblyChannel"; // Random number - don't know if it needs to be specific
I've remove the comment as well :)

2021-11-22 15:37 UTC, tomkirbygreen approved these changes
Martin and I have spoken about this and he's going to take a look-see at the points raise here in his iOS PR which builds upon this one.

2021-11-22 15:39 UTC, merged