iOs push app + integration implementation
ably/ably-dotnet pull request #1056
Opened 2021-11-22 10:37 UTC by marto83

This completes the push notification integration for iOs. 

There will be a PR for the documentation coming up next.

2021-11-23 06:39 UTC, tomkirbygreen requested changes
Why is the `delta-codec` submodule part of this PR please?

2021-11-23 06:39 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush.iOS/DotnetPush.iOS.csproj
> +    <CodesignKey>Apple Development: Martin Georgiev (M8ZL9UMJP9)</CodesignKey>
Are you happy leaving personal identifiers like this in public source code?

2021-11-23 06:39 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/AblySettings.cs
> +            get => Preferences.Get(ClientIdPreferenceKey, string.Empty, "Ably_Device");
Can we add `private const string AblyDevice = "AblyDevice";` at line 12 and replace this the subsequent three instances of the repeated string literal please.

2021-11-23 06:39 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/ViewModels/BaseViewModel.cs
> +            [CallerMemberName] string propertyName = "",
`string.Empty` please.

2021-11-23 06:39 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/ViewModels/SubscribeViewModel.cs
> +            // pushRealtime.OnActivationSta teMachineChangeState((current, next) =>
Did you mean to leave this commented out  code here?

2021-11-23 06:39 UTC, tomkirbygreen commented on examples/NotificationsPublisher/AppLogger.cs
> +        public List<string> Messages { get; } = new ();
Isn't this a [C# 9 language feature](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new). I thought we couldn't use C# 9, or do I have that wrong?

2021-11-23 17:46 UTC, marto83 commented on examples/NotificationsPublisher/AppLogger.cs
> +        public List<string> Messages { get; } = new ();
It is but because this is a standalone app I can use .net 5 + c# 9.0 :)

2021-11-23 22:13 UTC, marto83 commented
> Why is the `delta-codec` submodule part of this PR please?

I'm not sure. I went through all the individual commits and I haven't checked in a new reference for the delta codec.

2021-11-23 22:13 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2014")]
Done. It's 2021 now.

2021-11-23 22:14 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +            var alert = "";
Done.

2021-11-23 22:14 UTC, marto83 commented on examples/DotnetPush/DotnetPush/AblySettings.cs
> +            get => Preferences.Get("ABLY_CLIENT_ID", string.Empty, "Ably_Device");
Done.

2021-11-23 22:17 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/MainActivity.cs
> +            var options = new ClientOptions();
Done

2021-11-23 22:17 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +            var options = new ClientOptions();
Done.

2021-11-23 22:18 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/DotnetPush.iOS.csproj
> +    <CodesignKey>Apple Development: Martin Georgiev (M8ZL9UMJP9)</CodesignKey>
I've removed them. Better to be empty because people will not have them installed anyway so it won't help

2021-11-23 22:18 UTC, marto83 commented on examples/DotnetPush/DotnetPush/AblySettings.cs
> +            get => Preferences.Get(ClientIdPreferenceKey, string.Empty, "Ably_Device");
Done

2021-11-23 22:19 UTC, marto83 commented on examples/DotnetPush/DotnetPush/ViewModels/BaseViewModel.cs
> +            [CallerMemberName] string propertyName = "",
You can't have string.Empty as a default parameter value.

2021-11-23 22:19 UTC, marto83 commented on examples/DotnetPush/DotnetPush/ViewModels/SubscribeViewModel.cs
> +            // pushRealtime.OnActivationSta teMachineChangeState((current, next) =>
I've removed it.

2021-11-24 10:22 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2014")]
Done

2021-11-24 10:23 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +                // recommended for security reasons. Please, review ably's best practise guide on Authentication
Done

2021-11-24 11:42 UTC, tomkirbygreen requested changes

2021-11-24 11:42 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush.Android/MainActivity.cs
> +using IO.Ably.Push.Android;
Sort `using` directives please.

2021-11-24 11:42 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/AblySettings.cs
> +            get => Preferences.Get(ClientIdPreferenceKey, string.Empty, "Ably_Device");
It is? The `get` and `set` still have their own copies of the string literal `"Ably_Device"`. I actually count 8 separate instances of `"Ably_Device"` over 4 files...

2021-11-24 11:42 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush/ViewModels/StateViewModel.cs
> +            var model = new StateModel();
Can we use object initialiser syntax please?

2021-12-02 11:26 UTC, marto83 commented on examples/DotnetPush/DotnetPush/AblySettings.cs
> +            get => Preferences.Get(ClientIdPreferenceKey, string.Empty, "Ably_Device");
I've removed `Ably_Device` where possible and created a new constant for `Ably_StateMachine` and `Ably_Device` that are used in the app. I couldn't reuse the one we have in Ably.Push because it's internal

2021-12-02 11:27 UTC, marto83 commented on examples/DotnetPush/DotnetPush/ViewModels/StateViewModel.cs
> +            var model = new StateModel();
Done.

2021-12-06 11:27 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/MainActivity.cs
> +using IO.Ably.Push.Android;
Done :)

2021-12-06 11:55 UTC, tomkirbygreen approved these changes

2021-12-06 11:55 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush.Android/MainActivity.cs
> +                // Please provide a way for AblyRealtime to connect to the services. Having API keys on mobile devices is not
`is not` _what_ ?

2021-12-06 11:55 UTC, tomkirbygreen commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +                // Please provide a way for AblyRealtime to connect to the services. Having API keys on mobile devices is not
`is not` _what_ ?

2021-12-06 12:13 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/MainActivity.cs
> +                // Please provide a way for AblyRealtime to connect to the services. Having API keys on mobile devices is not
`is not recommended` - good spot thank you

2021-12-06 12:18 UTC, marto83 commented on examples/DotnetPush/DotnetPush.Android/MainActivity.cs
> +                // Please provide a way for AblyRealtime to connect to the services. Having API keys on mobile devices is not
I've pushed a fix.

2021-12-06 12:20 UTC, marto83 commented on examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
> +                // Please provide a way for AblyRealtime to connect to the services. Having API keys on mobile devices is not
Fixed.

2021-12-07 07:02 UTC, merged