Push/documentation
ably/ably-dotnet pull request #1071
Opened 2021-12-06 10:03 UTC by marto83

I've added a main document describing how to setup push notification for you app based on the documentation Ben did for flutter. 
Remaining: 
* Notification Publisher Readme
* DotNetPush sample app Readme

2021-12-07 15:49 UTC, tomkirbygreen requested changes

2021-12-07 15:49 UTC, tomkirbygreen commented on Push README.md
> +**iOS**: If the app is in the background / terminated, the ably sdk doesn't provide the functionality to configure / extend alert notifications on iOS, and these will automatically be shown to the us
"ably" => "Ably".

2021-12-07 15:49 UTC, tomkirbygreen commented on examples/NotificationsPublisher/Readme.md
> +- Connect to ably
"ably" => "Ably".

2021-12-09 23:51 UTC, marto83 commented on Push README.md
> +- Provide ably with the FCM server key: In your [firebase project settings](https://knowledge.ably.com/where-can-i-find-my-google/firebase-cloud-messaging-api-key), create or use an existing cloud me
Updated

2021-12-09 23:52 UTC, marto83 commented on Push README.md
> +Push Notifications allow you to reach users who have your application in the foreground, background and terminated, including when your application is not connected to Ably. Push notifications allow
I've updated the first paragraph

2021-12-09 23:52 UTC, marto83 commented on Push README.md
> +- Requires initialising AblyRealtime: Currently activating push notifications for a device requires an instance of AblyRealtime which gets instantiated when the application starts up. Please, submit
Done.

2021-12-09 23:52 UTC, marto83 commented on Push README.md
> +The DotNetPush app contains an example of how to use the Push Notification functionality. (TODO: Add links to github once PRs have been approved)
I've added links to the DotnetPush cs files

2021-12-09 23:52 UTC, marto83 commented on Push README.md
> +- The first step is to initialise the specific mobile device. You can achieve this by using either `AppleMobileDevice.Initialise` or `AndroidModileDevice.Initialise`. To initialise you need to pass a
Done

2021-12-09 23:52 UTC, marto83 commented on Push README.md
> +```csharp
Done

2021-12-09 23:52 UTC, marto83 commented on Push README.md
> +**iOS**: If the app is in the background / terminated, the ably sdk doesn't provide the functionality to configure / extend alert notifications on iOS, and these will automatically be shown to the us
Done

2021-12-09 23:52 UTC, marto83 commented on examples/NotificationsPublisher/Readme.md
> +- Connect to ably
Done

2021-12-13 12:10 UTC, tomkirbygreen approved these changes

2021-12-13 12:22 UTC, merged