Fix channel presence skipped test
ably/ably-dotnet pull request #1076
Opened 2021-12-26 10:32 UTC by sacOO7

- Fixes #848

2022-01-04 12:18 UTC, tomkirbygreen requested changes

2022-01-04 12:18 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/Rest/PresenceSandboxSpecs.cs
> +            channel.Should().NotBeNull();
How does this fix the test please?

2022-01-04 20:03 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Rest/PresenceSandboxSpecs.cs
> +            channel.Should().NotBeNull();
Same as https://github.com/ably/ably-dotnet/pull/1078#discussion_r778353143.

2022-01-05 06:50 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/Rest/PresenceSandboxSpecs.cs
> +            channel.Should().NotBeNull();
Thank you for the clarification Sachin. Please update the original commit message to include:

1. A link the related GitHub issue.
2. Details of the testing protocol, this can be something like "I ran the test multiple times locally and under CI and it passed every time there I conclude that can remove the 'Skip' because...".

The right place to capture any details about _why_ one thinks the test is failing would I suggest be in the associated GitHub Issue.

2022-01-05 18:12 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Rest/PresenceSandboxSpecs.cs
> +            channel.Should().NotBeNull();
Done

2022-01-06 16:07 UTC, tomkirbygreen approved these changes

2022-01-06 16:07 UTC, merged