Fixed RTP19
ably/ably-dotnet pull request #1078
Opened 2022-01-01 18:02 UTC by sacOO7

- Fixes #840

2022-01-04 12:21 UTC, tomkirbygreen requested changes
I don't understand how this fixes the test. Are you implying that there have been back end changes and the test _as is_ is correct?

2022-01-04 12:21 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +            [Theory]
_How_ does this fix the test please?

2022-01-04 20:01 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +            [Theory]
Yes, I tried running the test multiple times and it doesn't seem to be failing. So, your hunch is correct, there might have been backend changes and the test is not failing anymore. Also, just an idea, from now on, we can add detailed information in the skip as to why the test is failing or error information related to failed test which can help while resolving test issues.

2022-01-04 20:03 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +            [Theory]
Also, I feel bad I couldn't find a way to fix the test, since as you can see, the test is not failing in the first place.

2022-01-05 06:48 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +            [Theory]
Thank you for the clarification Sachin. Please update the original commit message to include:

1. A link the related GitHub issue.
2. Details of the testing protocol, this can be something like "I ran the test multiple times locally and under CI and it passed every time there I conclude that can remove the 'Skip' because...".

2022-01-05 18:11 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +            [Theory]
Done

2022-01-06 11:03 UTC, tomkirbygreen approved these changes

2022-01-06 11:03 UTC, merged