Presence map behavior
ably/ably-dotnet pull request #1079
Opened 2022-01-02 20:08 UTC by sacOO7

- Fixes #837

2022-01-14 07:50 UTC, tomkirbygreen requested changes

2022-01-14 07:50 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                List<PresenceMessage> receivedPresenceMsgs = new List<PresenceMessage>();
Use `var` please to avoid repeating the type from the RHS to the LHS.

2022-01-14 07:50 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/TestExtensions.cs
> +            var transport = ((AblyRealtime)client).ConnectionManager.Transport as TestTransportWrapper;
Since this is a hard requirement, why don't we change the `as` cast to a regular 'C style' cast, this will throw a `InvalidCastException` for us.

2022-01-16 06:38 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                var n = 0;
Please revert this. Where `var` gets its value is where the type is clearly stated on the right hand side of the expression so the following are good uses of `var`:

```
var a = new List<Foo>();    // Rather than 'Foo a = new List<Foo>();'
var b = Create<Bar>();    // Rather than 'Bar b = Create<Bar>();'
```

But using `var` in place of a built-in type such as `int`, `float` and `long` etc does not add value. So please avoid replacing:

```
int x = 0;
```
with:
```
var x = 0;
```
Since following that path leads us to (before) `long y = 0;` => `var y = (long)0;`.

2022-01-16 09:21 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                var n = 0;
Sure, this works

2022-01-18 05:44 UTC, tomkirbygreen approved these changes

2022-01-18 05:44 UTC, merged