Push platform specific packages
ably/ably-dotnet pull request #1086
Opened 2022-01-11 22:43 UTC by marto83

Added nuspec files for both android and ios. Updated the build script to add a new target for creating packages for the push projects. Add a shell script `package-push.sh` to run the build and output the packages in the root directory.

Things for review:
1. Package names. Our main package is called `ably.io` however I don't like the sound of `ably.io.push.android` so I called it `ably.push.android`. What do you think? I'm happy to fall back to the longer version.
2. Package descriptions. Please review 🙏🏼 
3. The build script will do a separate build for the main library and the push packages. I tried to make it happen all at once but the main build needs `windows` for .net framework and the push packages need `macos` otherwise the ios package doesn't build. 

Once we have the packages the next step will be to setup a myget repo and push them there for an internal test before pushing them to nuget.org

2022-01-12 06:02 UTC, tomkirbygreen requested changes
With respect to package names, whilst I'm sympathetic when it comes to wanting a package name that 'reads' better I think we should follow the established (ugly?) pattern and go with `ably.io.push.android` and `ably.io.push.ios` respectively.

2022-01-12 06:02 UTC, tomkirbygreen commented on nuget/io.ably.push.ios.nuspec
> +          <group>
Do we need this empty group?

2022-01-12 06:11 UTC, sacOO7 commented
> With respect to package names, whilst I'm sympathetic when it comes to wanting a package name that 'reads' better I think we should follow the established (ugly?) pattern and go with `ably.io.push.android` and `ably.io.push.ios` respectively.

Yes, and I would also recommend keeping the package name in sync with a respective namespace in the code.

2022-01-12 10:18 UTC, marto83 commented on nuget/io.ably.push.ios.nuspec
> +          <group>
we can remove it. I'll do that shortly.

2022-01-12 10:18 UTC, marto83 commented
Thanks for the comments guys. I'm going to update the package names.

2022-01-14 10:09 UTC, tomkirbygreen approved these changes

2022-01-14 18:14 UTC, sacOO7 approved these changes

2022-01-16 06:42 UTC, tomkirbygreen requested changes
Please resolve the merge conflicts.

2022-01-18 11:43 UTC, tomkirbygreen approved these changes

2022-01-18 11:43 UTC, merged