Presence leave while syncing
ably/ably-dotnet pull request #1092
Opened 2022-01-17 18:01 UTC by sacOO7

- Fixes #839

2022-01-18 11:37 UTC, tomkirbygreen requested changes

2022-01-18 11:37 UTC, tomkirbygreen commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                client.BlockActionFromReceiving(ProtocolMessage.MessageAction.Sync);
I think for now, given that we only have one use case for this API it would be better packaged as a local function, possibly called 'BlockAblyServerSentSyncAction' (that way we can lose the comment).

2022-01-19 14:43 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                client.BlockActionFromReceiving(ProtocolMessage.MessageAction.Sync);
Done !

2022-01-20 04:42 UTC, tomkirbygreen approved these changes
Nice. Personally I would have been tempted to make `BlockAblyServerSentSyncAction` a local / nested function of `GetChannel` thus further reducing its scope.

2022-01-20 04:42 UTC, merged