Update 'README.md'
ably/ably-dotnet pull request #1117
Opened 2022-02-11 13:45 UTC by tomkirbygreen

Update `README.md` for .NET 6, Unity and 'legacy' URLs of the form `ably.io`.

2022-02-11 14:46 UTC, owenpearson requested changes
LGTM, just one possible typo and a couple of minor suggestions.

2022-02-11 14:46 UTC, owenpearson commented on README.md
> +The `ably_dotnet` library fully supports Ably's push notifications. The feature set consists of two distinct areas: [Push Admin](https://ably.com/documentation/general/push/admin), [Device Push Notif
Is the underscore here meant to be a hyphen? I can't find any references to `ably_dotnet` anywhere by way of Google.

2022-02-11 14:46 UTC, owenpearson commented on README.md
> +In .NET Framework projects, we discovered issues with the .NET implementation of the websocket protocol during times of high load with large payloads (over 50kb). This is better described in https://
Consider 'WebSocket' (this is how it's stylised in the original RFC and on wikipedia)

2022-02-11 14:46 UTC, owenpearson commented on README.md
> +The build scripts are written using ```fake``` and need to be run on Windows with Visual Studio 2017 or Visual Studio 2019 or Visual Studio 2022 installed. Fake and nuget.exe can be installed via [ch
This sentence reads a bit odd now, consider:
- "and need to be run on Windows with Visual Studio 2017, 2019, or 2022"
- "and need to be run on Windows with Visual Studio (versions 2017, 2019, and 2022 are supported)"
- "and need to be run on Windows with Visual Studio (versions 2017 upwards are supported)"

2022-06-20 08:54 UTC, tomkirbygreen commented
Closing this as we're taking a slightly different route to .NET 6 by way of removing Windows 7 as a supported platform first.

2022-06-20 08:54 UTC, closed without merging