Unity integration GitHub action
ably/ably-dotnet pull request #1120
Opened 2022-02-16 03:13 UTC by sacOO7

- Setup unity build using gameCI
- Setup basic GitHub action for Unity license activation and editmode+playmode tests

2022-02-23 14:43 UTC, QuintinWillison requested changes
I've done a brief, first-pass review.

I would have expected to see something added to the documentation, in respect of contributing guidelines, explaining what `UNITY_LICENSE` is. Where is it obtained from? What format is it in? Can it expire? That kind of thing.

2022-02-23 14:43 UTC, QuintinWillison commented on .github/workflows/unity-activation.yml
> +      # Request manual activation file
This comment is superfluous as the step has this clearly indicated in `name`.

2022-02-23 14:43 UTC, QuintinWillison commented on README.md
> +6. Create a PR and grain approvals for it, then merge that to `main`.
I realise you inherited this typo, but:

```suggestion
6. Create a PR and gain approvals for it, then merge that to `main`.
```

2022-02-23 14:43 UTC, QuintinWillison commented on README.md
> +11. Visit `Unity / Generate Ably Unity Package (push)` under latest workflow in a new tab, click on `summary` on the left nav-bar, download `AblyUnity` artifact from the bottom, unzip it and rename f
I don't understand this sentence and I think the title you refer to is invalid given current state of workflows presented in this PR.

2022-02-23 14:43 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +on: [push]
We never run anything on `push`. See [here](https://github.com/ably/engineering/blob/main/sdk/github.md#triggers-on), if that's _really_ what this needs.

2022-02-23 14:43 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +        projectPath:
This node only has one value, so why's it in the matrix?

2022-02-23 14:43 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +        unityVersion:
This node only has one value, so why's it in the matrix?

2022-02-23 14:43 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +          lfs: true
Why do you need to specify this? I find this surprising, given none of the existing workflows in this repository need to. If anything, per the other workflows, I would expect you to need to specify `recursive: true`.

Also applies to the same, later on in this file.

2022-02-23 14:43 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +      - uses: actions/cache@v2
Do you not need to include input from the matrix here?

2022-02-23 14:43 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +        uses: game-ci/unity-test-runner@v2
This is a third party action. Why does it need the `GITHUB_TOKEN`?

2022-02-24 07:56 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +on: [push]
Actually, we are using it in our existing workflows 
https://github.com/ably/ably-dotnet/blob/f00b73f13605d479972f5d8f72c23b3cdd749501/.github/workflows/build-and-test-windows.yml#L1-L2
https://github.com/ably/ably-dotnet/blob/f00b73f13605d479972f5d8f72c23b3cdd749501/.github/workflows/build-and-test-linux.yml#L1-L2
https://github.com/ably/ably-dotnet/blob/f00b73f13605d479972f5d8f72c23b3cdd749501/.github/workflows/build-and-test-macos.yml#L1-L2

2022-02-24 08:07 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +        uses: game-ci/unity-test-runner@v2
Actually, it's required to upload XML test results back under actions. They are visible in a readable format.  You can check
https://github.com/sac-fork/ably-unity/actions/runs/1891863637

2022-02-24 08:07 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +          lfs: true
Updated !

2022-02-24 08:08 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +        unityVersion:
Fixed!

2022-02-24 08:08 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +        projectPath:
Fixed!

2022-02-24 08:08 UTC, sacOO7 commented on README.md
> +11. Visit `Unity / Generate Ably Unity Package (push)` under latest workflow in a new tab, click on `summary` on the left nav-bar, download `AblyUnity` artifact from the bottom, unzip it and rename f
Updated

2022-02-24 08:08 UTC, sacOO7 commented on README.md
> +6. Create a PR and grain approvals for it, then merge that to `main`.
Fixed!

2022-02-24 08:08 UTC, sacOO7 commented on .github/workflows/unity-activation.yml
> +      # Request manual activation file
Fixed!

2022-02-24 08:11 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +      - uses: actions/cache@v2
Actually yes, it's to denote the type of test it's running. Matrix will run EditMode and PlayMode tests. The result should look like this 
https://github.com/sac-fork/ably-unity/actions/runs/1891863637

2022-02-24 08:19 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +        uses: game-ci/unity-test-runner@v2
I have removed `GITHUB_TOKEN` access from the `gameci/test-runner` .  Now, XML results will not be visible under actions/workflow nav-bar. Instead, test artifacts needs to be downloaded separately from `workflow summary`

2022-03-02 15:58 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +on: [push]
Existing workflows are out-of-date. I've fixed that in https://github.com/ably/ably-dotnet/pull/1132

2022-03-02 16:01 UTC, QuintinWillison commented on README.md
> +11. Visit `Unity / Generate Ably Unity Package (push)` under latest workflow in a new tab, click on `summary` on the left nav-bar, download `AblyUnity` artifact from the bottom, unzip it and rename f
It looks like this was done in https://github.com/ably/ably-dotnet/pull/1120/commits/01cda8f6bcc26c9660e11151f41e696635a74cef

2022-03-02 18:42 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +on: [push]
Thanks !!

2022-03-03 07:18 UTC, sacOO7 commented on .github/workflows/unity-build-and-test.yml
> +on: [push]
Updated

2022-03-03 14:40 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +on: [push]
https://github.com/ably/ably-dotnet/pull/1120/commits/e1476efd8963662b21299f5be90716d4540b4e84

2022-03-03 15:52 UTC, QuintinWillison commented on .github/workflows/unity-build-and-test.yml
> +      - uses: actions/cache@v2
I'll admit I don't really understand what you're saying [in your response](https://github.com/ably/ably-dotnet/pull/1120#discussion_r813636695) (for example, your first sentence includes "it's" twice, where it's not clear what either instance of that word refers to):

> Actually yes, it's to denote the type of test it's running. Matrix will run EditMode and PlayMode tests. The result should look like this
> https://github.com/sac-fork/ably-unity/actions/runs/1891863637

Regardless, this is harmless enough, I just wanted to check that you were confident in what you were caching and when. I shall resolve this conversation.

2022-03-03 15:53 UTC, QuintinWillison commented
I'll take another look at this pull request after @tomkirbygreen has submitted a review.

2022-06-09 10:20 UTC, tomkirbygreen commented
Spoke with @sacOO7 prior to closing this. We are taking a different approach, that of integrating Unity Cloud Build into our GitHub hosted CI.

2022-06-09 10:20 UTC, closed without merging