Update netstandard assemblyInfo
ably/ably-dotnet pull request #1125
Opened 2022-02-20 19:19 UTC by sacOO7

- Fixes #1123

2022-02-23 10:17 UTC, tomkirbygreen requested changes

2022-02-23 10:17 UTC, tomkirbygreen commented on src/IO.Ably.NETStandard20/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Assets.Tests.AblySandbox")]
Would it be possible to follow the established namespace scheme. Something like: 

```
IO.Ably.Tests.Unity.Sandbox
IO.Ably.Tests.Unity.EditMode
IO.Ably.Tests.Unity.PlayMode
```

2022-02-23 12:18 UTC, sacOO7 commented on src/IO.Ably.NETStandard20/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Assets.Tests.AblySandbox")]
Actually, it has to do with the project structure established inside unity project. Since it's already a unity project, the new convention will add the extra directory to the project.  I think we can approve it for now, and then think about refactoring later on, since it will unblock lot of our other PR's.

2022-02-23 15:58 UTC, tomkirbygreen approved these changes

2022-03-07 15:47 UTC, QuintinWillison approved these changes

2022-03-08 07:51 UTC, merged