[Unity Integration] Editmode and Playmode tests
ably/ably-dotnet pull request #1128
Opened 2022-02-23 10:19 UTC by sacOO7

- Created a seaparate AblySandbox assembly definition to access Ably sandbox API.
- Added unity editmode and playmode tests

2022-03-04 07:11 UTC, tomkirbygreen requested changes

2022-03-04 07:11 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +            Logger.Debug("Test end disposing connections: " + _realtimeClients.Count);
Use string interpolation please.

2022-03-04 07:11 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                catch (Exception ex)
Can we not catch something more specific?

2022-03-04 07:11 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                    Logger.Error("Error disposing Client: " + ex.Message);
Use string interpolation please.

2022-03-04 07:11 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                catch (Exception ex)
OK, but what kinds of Exceptions have you observed? Can we just catch those (assuming they're reasonable).

2022-03-04 07:11 UTC, tomkirbygreen commented on unity/Assets/Tests/EditMode/AuthSandboxSpecs.cs
> +using FluentAssertions;
I'd rather we didn't take a dependency on this when there are perfectly serviceable assertions in the Base Class Library.

2022-03-04 07:11 UTC, tomkirbygreen commented on unity/Assets/Tests/PlayMode/AuthSandboxSpecs.cs
> +using FluentAssertions;
I'd rather we didn't take a dependency on this when there are perfectly serviceable assertions in the Base Class Library.

2022-03-04 07:11 UTC, tomkirbygreen commented on unity/Assets/Tests/PlayMode/AuthSandboxSpecs.cs
> +            while (!task.IsCompleted) { yield return null; }
Reformat for multiline please, this 'line' and the next.

2022-03-05 18:14 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblyCollectionFixture.cs
> +        internal AblyHttpClient GetHttpClient(string environment = null)
Marked other methods in the file as `internal`, since they will be used internally by the package.

2022-03-05 18:15 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            if (environment != null)
I have removed `sandbox` as default param value, now it can be `null` if nothing is passed

2022-03-05 18:52 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +        public async Task SetupStats()
Added test for `stats` - `unity/Assets/Tests/EditMode/StatsSandBoxSpecs.cs`

2022-03-05 18:52 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +        private static async Task SetupSampleStats(TestEnvironmentSettings settings)
Added test for `stats` - `unity/Assets/Tests/EditMode/StatsSandBoxSpecs.cs`

2022-03-05 18:53 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +        public static string _statsFixture = @"
Added test for `stats` - `unity/Assets/Tests/EditMode/StatsSandBoxSpecs.cs`

2022-03-05 19:17 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +                catch (Exception)
Actually, I am reusing most of the code from original `AblySandboxSpec`. I think martin might have a good reason to use it, since we capture all types of errors and then retry. 
https://github.com/ably/ably-dotnet/blob/f3272d61082496042260e8949319d5630cb7f62c/src/IO.Ably.Tests.Shared/Infrastructure/AblySandboxFixture.cs#L82-L90

2022-03-05 19:29 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestTransportWrapper.cs
> +                catch (Exception ex)
I am referring to original source code for `TestTransportWrapper`. There must be a good reason not to catch specific exception and handle every other type of error same way.
https://github.com/ably/ably-dotnet/blob/f3272d61082496042260e8949319d5630cb7f62c/src/IO.Ably.Tests.Shared/Infrastructure/TestTransportWrapper.cs#L42-L70

2022-03-05 19:44 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblyCollectionFixture.cs
> +            return new ClientOptions { Key = key ?? FirstValidKey, Tls = Tls, Environment = env, AutomaticNetworkStateMonitoring = false};
Done!

2022-03-06 08:47 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +        private static async Task<TestEnvironmentSettings> Initialise(string environment = "sandbox")
Parameter removed, calling it with `sandbox` explicitly

2022-03-06 08:47 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            // JObject testAppSpec = JObject.Parse(ResourceHelper.GetResource("test-app-setup.json"));
Done!

2022-03-06 08:50 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static Task<TimeSpan> WaitForState(this AblyRealtime realtime, ConnectionState awaitedState, TimeSpan? waitSpan = null)
1. Renamed to `AblyRealtimeExtensions`
2. Actually this class covers `test-utils` required for running integration tests. I am referencing the implementation from original source code. I think keeping it generic/flexible will help for fixing flaky tests. Also, for future tests, we have the option to increase the timeout for a specific test.

2022-03-06 09:09 UTC, sacOO7 commented on unity/Assets/Tests/PlayMode/AuthSandboxSpecs.cs
> +            while (!task.IsCompleted) { yield return null; }
Removed, we will be using `UniTask` library to convert `IEnumerable` to `CoRoutine`.  Also, code is more readable and not much duplication.

2022-03-06 09:11 UTC, sacOO7 commented on unity/Assets/Tests/PlayMode/AuthSandboxSpecs.cs
> +using FluentAssertions;
Actually, we are reusing the code from `Dotnet SDK`. It uses `FluentAssertions` library. So to avoid a mismatch, I am reusing the same library. I will create an issue to safely port assertions to the base library.

2022-03-06 11:03 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static async Task ProcessMessage(this IRealtimeClient client, ProtocolMessage message)
Actually, `ProcessMessage` is an abstraction to `ProcessCommands`, we will need it for implementing `message` specific tests in the future, especially `Presence` related tests.

2022-03-06 11:04 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +            if (resourceStream == null)
Same as https://github.com/ably/ably-dotnet/pull/1128#discussion_r820139878

2022-03-06 11:04 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +            if (resourceStream == null)
Same as https://github.com/ably/ably-dotnet/pull/1128#discussion_r820139878

2022-03-06 11:04 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                catch (Exception ex)
Same as https://github.com/ably/ably-dotnet/pull/1128#discussion_r820139878

2022-03-06 11:04 UTC, sacOO7 commented on unity/Assets/Tests/EditMode/AuthSandboxSpecs.cs
> +using FluentAssertions;
Actually, we are reusing the code from Dotnet SDK. It uses FluentAssertions library. So to avoid a mismatch, I am reusing the same library. I will create an issue to safely port assertions to the base library.

2022-03-06 11:05 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +                throw new Exception(msg);
Same as https://github.com/ably/ably-dotnet/pull/1128#discussion_r820139878

2022-03-06 11:09 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            AblyHttpClient client = settings.GetHttpClient(environment);
Moved !

2022-03-06 11:09 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            // await SetupSampleStats(settings);
Removed !

2022-03-06 11:10 UTC, sacOO7 commented on unity/Assets/Tests/PlayMode/PlayMode.asmdef
> +        "BoundfoxStudios.FluentAssertions",
Same as https://github.com/ably/ably-dotnet/pull/1128#discussion_r820216995

2022-03-06 11:10 UTC, sacOO7 commented on unity/ProjectSettings/PackageManagerSettings.asset
> +    - com.boundfoxstudios.fluentassertions
Same as https://github.com/ably/ably-dotnet/pull/1128#discussion_r820216995

2022-03-06 11:22 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +            return Wait(TimeSpan.FromSeconds(16));
It's used from the original `ConnectionAwaiter` class, I will put it as a static value. Thanks

2022-03-06 11:26 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +        public ConnectionAwaiter(Connection connection, params ConnectionState[] awaitedStates)
That is true! I think it's been kept generic/flexible to accept a range of values. Although multiple values are not required as of now, I am sure, we will need them in the future.

2022-03-06 11:26 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static string AddRandomSuffix(this string str)
Moved!

2022-03-06 11:26 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static async Task WaitForState(this IRealtimeChannel channel, ChannelState awaitedState = ChannelState.Attached, TimeSpan? waitSpan = null)
Moved!

2022-03-06 12:20 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +            var tResult = _taskCompletionSource.Task;
Fixed !

2022-03-06 12:20 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +            var tCompleted = await Task.WhenAny(tResult, Task.Delay(timeout)).ConfigureAwait(false);
Fixed !

2022-03-06 12:20 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static async Task<bool> WaitSync(this Presence presence, TimeSpan? waitSpan = null)
Moved under `channelExtensions`, will be required for presence tests

2022-03-06 12:21 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +            byte[] data = new byte[resourceStream.Length];
Removed resource reader code, since it's not required anymore !

2022-03-06 12:33 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +            Logger.Debug("Test end disposing connections: " + _realtimeClients.Count);
Done

2022-03-06 12:33 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                    Logger.Error("Error disposing Client: " + ex.Message);
Done

2022-03-06 12:33 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                catch (Exception ex)
Same as https://github.com/ably/ably-dotnet/pull/1128#discussion_r820139878

2022-03-06 12:34 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +            return Wait(TimeSpan.FromSeconds(16));
Done

2022-03-25 09:25 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +        private static async Task<TestEnvironmentSettings> Initialise(string environment = "sandbox")
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:25 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            if (environment != null)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:25 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            // JObject testAppSpec = JObject.Parse(ResourceHelper.GetResource("test-app-setup.json"));
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:25 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            AblyHttpClient client = settings.GetHttpClient(environment);
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:25 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +            // await SetupSampleStats(settings);
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:26 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +                catch (Exception)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:26 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +        private static async Task SetupSampleStats(TestEnvironmentSettings settings)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:26 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +        public ConnectionAwaiter(Connection connection, params ConnectionState[] awaitedStates)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:26 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +            return Wait(TimeSpan.FromSeconds(16));
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:26 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +            var tResult = _taskCompletionSource.Task;
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:26 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/ConnectionAwaiter.cs
> +            var tCompleted = await Task.WhenAny(tResult, Task.Delay(timeout)).ConfigureAwait(false);
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:26 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static string AddRandomSuffix(this string str)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static Task<TimeSpan> WaitForState(this AblyRealtime realtime, ConnectionState awaitedState, TimeSpan? waitSpan = null)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static async Task ProcessMessage(this IRealtimeClient client, ProtocolMessage message)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static async Task<bool> WaitSync(this Presence presence, TimeSpan? waitSpan = null)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +        public static string _statsFixture = @"
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/TestTransportWrapper.cs
> +                catch (Exception ex)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +            if (resourceStream == null)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                    Logger.Error("Error disposing Client: " + ex.Message);
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:27 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                catch (Exception ex)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:28 UTC, tomkirbygreen commented on unity/Assets/Tests/PlayMode/AuthSandboxSpecs.cs
> +            while (!task.IsCompleted) { yield return null; }
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:28 UTC, tomkirbygreen commented on unity/Assets/Tests/EditMode/AuthSandboxSpecs.cs
> +using FluentAssertions;
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:28 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +            byte[] data = new byte[resourceStream.Length];
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:28 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +                throw new Exception(msg);
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:28 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +            Logger.Debug("Test end disposing connections: " + _realtimeClients.Count);
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:29 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/UnitySandbox.cs
> +                catch (Exception ex)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:29 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/TestUtils.cs
> +            if (resourceStream == null)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:29 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/SandboxSpecExtension.cs
> +        public static async Task WaitForState(this IRealtimeChannel channel, ChannelState awaitedState = ChannelState.Attached, TimeSpan? waitSpan = null)
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-03-25 09:29 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandboxFixture.cs
> +        public async Task SetupStats()
Resolving this as I'll be taking over this PR while Sachin visits PHP land.

2022-04-05 05:10 UTC, merged