Unity integration/example
ably/ably-dotnet pull request #1134
Opened 2022-03-07 11:48 UTC by sacOO7

- Created Ably UI console app.
- Added basic functionality for showing active connection with the server.

![Ably console](https://user-images.githubusercontent.com/16723785/157028812-02a0c3d7-2e9f-4d8c-b364-899f18cad793.JPG)

2022-03-08 07:26 UTC, tomkirbygreen commented
This looks great Sachin. Looking forward to getting it running on my VM and then I'll review the code. Thank you! :-)

2022-04-05 07:09 UTC, tomkirbygreen commented
Could we please change the `Example` folder to be a little more specific and allow for future examples. So I would suggest changing `unity/Assets/Ably/Example/` to `unity/Assets/Ably/Examples/Chat/`. Thank you.

2022-04-05 07:38 UTC, tomkirbygreen requested changes
Just a few action points.

2022-04-05 07:38 UTC, tomkirbygreen commented on unity/Assets/Ably/Example/AblyChannelUiConsole.cs
> +
Single line between functions please.

2022-04-05 07:38 UTC, tomkirbygreen commented on unity/Assets/Ably/Example/AblyConsole.cs
> +        private static string _apiKey = "";
`= String.Empty;` please.

2022-04-05 07:38 UTC, tomkirbygreen commented on unity/Assets/Ably/Example/AblyConsole.cs
> +            if (_isConnected)
Missing `{...}` for `if` and `else` blocks.

2022-04-05 07:38 UTC, tomkirbygreen commented on unity/Assets/Ably/Example/AblyConsole.cs
> +}
Missing newline.

2022-04-05 07:38 UTC, tomkirbygreen commented on unity/Assets/Ably/Example/AblyChannelUiConsole.cs
> +namespace Assets.Ably.Example
This namespace needs to change to `namespace Asserts.Ably.Examples.Chat` in line with the comment about renaming the project from `Example` to `Examples/Chat`.

2022-04-05 07:55 UTC, sacOO7 commented on unity/Assets/Ably/Example/AblyChannelUiConsole.cs
> +
Done

2022-04-05 07:55 UTC, sacOO7 commented on unity/Assets/Ably/Example/AblyConsole.cs
> +        private static string _apiKey = "";
Updated to `Your_Api-key_Here`

2022-04-05 07:55 UTC, sacOO7 commented on unity/Assets/Ably/Example/AblyConsole.cs
> +            if (_isConnected)
done

2022-04-05 07:55 UTC, sacOO7 commented on unity/Assets/Ably/Example/AblyChannelUiConsole.cs
> +namespace Assets.Ably.Example
done

2022-04-05 18:10 UTC, sacOO7 commented on unity/Assets/Ably/Example/AblyConsole.cs
> +}
done

2022-04-08 09:19 UTC, ikbalkaya requested changes

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +            _uiConsole.LogAndDisplay($"Successfully unsubscribed to channel <b>{channelName}</b>");
```suggestion
            _uiConsole.LogAndDisplay($"Successfully unsubscribed from channel <b>{channelName}</b>");
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private void UnsubscribeChannelHandler()
Not sure if naming methods ending with -Handler is a common practice, but this method name sounds more like an object. Wouldn't it be cleaner if it was `UnsubscribeFromChannel`?

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private void UnsubscribeChannelHandler()
```suggestion
        private void UnsubscribeFromChannel()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private async void ChannelMessageHistoryHandler()
```suggestion
        private async void LoadChannelMessageHistory()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private async void PublishClickHandler()
```suggestion
        private async void PublishMessage()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal void PresenceSubscribeClickHandler()
```suggestion
        internal void SubscribeToPresence()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal void PresenceUnsubscribeClickHandler()
```suggestion
        internal void UnsubscribeFromPresence()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal async void GetPresenceClickHandler()
```suggestion
        internal async void GetPresence()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal async void PresenceMessageHistoryClickHandler()
```suggestion
        internal async void GetPresenceMessageHistory()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal async void PresenceLeaveClickHandler()
```suggestion
        internal async void LeavePresence()
```

2022-04-08 09:19 UTC, ikbalkaya commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +                : $"Error leaving presence to channel <b>{channelName}</b>, failed with error <b>{result.Error.Message}</b>");
```suggestion
                : $"Error leaving presence from channel <b>{channelName}</b>, failed with error <b>{result.Error.Message}</b>");
```

2022-04-08 15:25 UTC, tomkirbygreen approved these changes
The actual logic is fine I think. There are some 'fit and finish' issues, but I don't know if they should hold things up.

2022-04-08 15:25 UTC, tomkirbygreen commented on unity/Assets/Ably/Examples/Chat/AblyConsole.cs
> +
Remove please.

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +            _uiConsole.LogAndDisplay($"Successfully unsubscribed to channel <b>{channelName}</b>");
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private void UnsubscribeChannelHandler()
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private void SubscribeChannelClickHandler()
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private async void ChannelMessageHistoryHandler()
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyChannelUiConsole.cs
> +        private async void PublishClickHandler()
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal void PresenceSubscribeClickHandler()
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal void PresenceUnsubscribeClickHandler()
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +            _uiConsole.LogAndDisplay($"Successfully unsubscribed to channel <b>{channelName}</b> for <b>Presence</b> messages");
done

2022-04-09 20:56 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal async void GetPresenceClickHandler()
done

2022-04-09 20:57 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal async void PresenceMessageHistoryClickHandler()
done

2022-04-09 20:57 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal async void PresenceEnterClickHandler()
done

2022-04-09 20:57 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +        internal async void PresenceLeaveClickHandler()
done

2022-04-09 20:57 UTC, sacOO7 commented on unity/Assets/Ably/Examples/Chat/AblyPresenceUiConsole.cs
> +                : $"Error leaving presence to channel <b>{channelName}</b>, failed with error <b>{result.Error.Message}</b>");
done

2022-04-10 05:12 UTC, tomkirbygreen commented
Looking good @sacOO7 , we'll just need to wait for @ikbalkaya to approve it assuming he's happy now.

2022-04-11 08:56 UTC, ikbalkaya approved these changes
LGTM

2022-04-11 09:13 UTC, merged