Unity integration/tests-refresh
ably/ably-dotnet pull request #1137
Opened 2022-03-28 09:40 UTC by tomkirbygreen

This PR is intended to replace Sachin's [PR](https://github.com/ably/ably-dotnet/pull/1128) (which I have reverted for now to Draft status). I've done this so that @sacOO7 can be a reviewer seeing as this was his baby and I've touched a lot of lines.

2022-03-28 12:32 UTC, tomkirbygreen commented
I would like to merge this directly to `main` as I feel it has immediate value and while we wait to hear from Unity with respect to which route we should take architecturally for our CI pipeline given Ably's in-house requirements, the work Sachin has done here is valid irrespective of the approach for building we finally take.

2022-03-30 10:25 UTC, ikbalkaya requested changes

2022-03-30 10:25 UTC, ikbalkaya commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +          ""_post_apps"": ""/* JSON body using in POST sandbox-rest.ably.io/apps request to set up the Test app */"",
Wouldn't it be cleaner to read this JSON from an external file 🤔

2022-03-30 10:25 UTC, ikbalkaya commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +          ""_post_apps"": ""/* JSON body using in POST sandbox-rest.ably.io/apps request to set up the Test app */"",
Wouldn't it be cleaner to read this JSON from an external file 🤔

2022-03-30 10:25 UTC, ikbalkaya commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +    {
And this

2022-03-30 10:25 UTC, ikbalkaya commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +    {
And this

2022-03-30 10:25 UTC, ikbalkaya commented on unity/Assets/Tests/AblySandbox/TestTransportWrapper.cs
> +                    }
What if `_wrappedTransport.BeforeDataProcessed == null`?

2022-03-30 10:25 UTC, ikbalkaya commented on unity/Assets/Tests/AblySandbox/TestTransportWrapper.cs
> +                    }
What if `_wrappedTransport.BeforeDataProcessed == null`?

2022-03-30 13:02 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +          ""_post_apps"": ""/* JSON body using in POST sandbox-rest.ably.io/apps request to set up the Test app */"",
I agree with that !! We have our current `.Net` sandbox implementation with `json` files for storing configuration. I tried to replicate the same in unity. Problem is, the text/json file becomes `TextAsset` in unity. I put some time into this and found out there is a different way to handle these `TextAsset` files. Rather than making code dependent on `TextAssets` and worrying about cross-platform compatibility, it was way easier to put `json string` inside `class` file. The pattern is not new, and is used where `config` is a lot obvious and doesn't need to be changed over time.

2022-03-31 09:39 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestTransportWrapper.cs
> +                    }
That's why we have optional invocation. If it's null, it will not execute the method.

2022-03-31 09:39 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestTransportWrapper.cs
> +                    }
That's why we have optional invocation. If it's null, it will not execute the method.

2022-03-31 09:40 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +          ""_post_apps"": ""/* JSON body using in POST sandbox-rest.ably.io/apps request to set up the Test app */"",
same as https://github.com/ably/ably-dotnet/pull/1137#discussion_r838516913

2022-03-31 09:40 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +    {
same as https://github.com/ably/ably-dotnet/pull/1137#discussion_r838516913

2022-03-31 09:41 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +    {
same as https://github.com/ably/ably-dotnet/pull/1137#discussion_r838516913

2022-03-31 09:42 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/TestTransportWrapper.cs
> +                    }
That's why we have optional invocation. If it's null, it will not execute the method.

2022-04-03 12:37 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandbox.cs
> +        public async Task AssertMultipleTimes(Func<Task> testAction, int maxNumberOfTimes, TimeSpan durationBetweenAttempts)
Renamed to `AssertWithRetries`

2022-04-03 12:38 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblyRealtimeExtensions.cs
> +                    await Task.Delay(50);
Created `Timeout` Constant

2022-04-03 12:38 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblyRealtimeExtensions.cs
> +            var realtime = (AblyRealtime)client;
Updated code, removed `AblyRealtime` cast

2022-04-03 12:38 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblyRealtimeExtensions.cs
> +        /// <returns></returns>
Removed the comment

2022-04-03 12:45 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandbox.cs
> +            _realtimeClients.Add(client);
Actually, this is derived from the original sandboxspec https://github.com/ably/ably-dotnet/blob/f3272d61082496042260e8949319d5630cb7f62c/src/IO.Ably.Tests.Shared/Rest/SandboxSpecs.cs#L92.
Since this is an interfacing method, we need to change it at both places. All of our tests at both sides are using the same method to get `realtime` instance.

2022-04-03 12:45 UTC, sacOO7 commented on unity/Assets/Tests/AblySandbox/AblySandbox.cs
> +            _realtimeClients.Add(client);
Actually, this is derived from the original sandboxspec https://github.com/ably/ably-dotnet/blob/f3272d61082496042260e8949319d5630cb7f62c/src/IO.Ably.Tests.Shared/Rest/SandboxSpecs.cs#L92.
Since this is an interfacing method, we need to change it at both places. All of our tests on both sides are using the same method to get `realtime` instance.

2022-04-03 12:46 UTC, sacOO7 approved these changes

2022-04-04 08:30 UTC, ikbalkaya approved these changes
LGTM thanks

2022-04-04 09:03 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/AblySandbox.cs
> +        public async Task AssertMultipleTimes(Func<Task> testAction, int maxNumberOfTimes, TimeSpan durationBetweenAttempts)
Resolving this having checked with Ikbal.

2022-04-04 09:04 UTC, tomkirbygreen commented on unity/Assets/Tests/AblySandbox/TestAppSetup.cs
> +          ""_post_apps"": ""/* JSON body using in POST sandbox-rest.ably.io/apps request to set up the Test app */"",
Resolving this having checked with Ikbal.

2022-04-04 09:04 UTC, merged