[Unity-Integration] SETUP and USAGE Documentation
ably/ably-dotnet pull request #1141
Opened 2022-04-05 05:13 UTC by sacOO7

- Added `README.md` file for unity package import in the code.
- Added `SETUP.md` for local unity development setup.
- Added `unity_editor_layout` file for unity editor layout.

2022-04-05 07:05 UTC, tomkirbygreen commented
Could we please change the single `.JPG` into a `.PNG` please, just like all the others.

2022-04-05 15:26 UTC, tomkirbygreen requested changes
Could we please change the `.JPG` into a `.PNG` so we just have the one bitmap type please.

2022-04-06 08:45 UTC, ikbalkaya requested changes
I'm not sure if that's true but I was wondering whether 'unity' should begin with uppercase 'u'. Apart from that I made some requests on typos

2022-04-06 08:45 UTC, ikbalkaya commented on unity/README.md
> +- Ably unity project supports both Mono and IL2CPP builds.
Should 'Unity' not start with upper case 🤔

2022-04-06 08:45 UTC, ikbalkaya commented on unity/README.md
> +- Make sure to [disable assembly validation](SETUP.md#disable-assembly-validation-error) if it fails due to conflict with internal newtonsoft json library.
Here, I think it would be nice to link to either to the mentioned library or the problem that's happening with it.

2022-04-06 08:45 UTC, ikbalkaya commented on unity/README.md
> +- NewtonSoft JSON DLL's can be removed, in case use of inbuilt Newtonsoft is preferred https://docs.unity3d.com/Packages/com.unity.nuget.newtonsoft-json@2.0/manual/index.html.
Typo 'DLLs' 🤔

2022-04-06 08:45 UTC, ikbalkaya commented on unity/SETUP.md
> +4. Basics of unity [Official Unity Manual](https://docs.unity3d.com/Manual/index.html) and [Unity Beginner Manual](https://docs.google.com/document/d/1TJSKoqsElTjnAVKy-nFcARGHthwv18PFdt8pnuorxvw/edit
I think "(Ignore if already know)" might be removed

2022-04-06 08:45 UTC, ikbalkaya commented on unity/SETUP.md
> +- Download and install git binary from https://git-scm.com/downloads (ignore if already installed)
This ignore warning as well

2022-04-06 08:45 UTC, ikbalkaya commented on unity/SETUP.md
> +- Unity projects are visible as a part of Unity Hub (list should be empty for none active projects)
typo 'none active' should be either 'non active' or 'inactive'

2022-04-06 08:45 UTC, ikbalkaya commented on unity/SETUP.md
> +- Select most recent LTS version and click on next to install the selected unity version.
Can this 'next' be highlighted as **ADD**? Not sure if there is a convention on that

2022-04-06 08:45 UTC, ikbalkaya commented on unity/SETUP.md
> +- All the tests should be available and shown under `EditMode.dll`
"All tests"

2022-04-06 08:45 UTC, ikbalkaya commented on unity/SETUP.md
> +- All the tests should be available and shown under `PlayMode.dll`
"All tests"

2022-04-06 12:09 UTC, sacOO7 commented on unity/SETUP.md
> +4. Basics of unity [Official Unity Manual](https://docs.unity3d.com/Manual/index.html) and [Unity Beginner Manual](https://docs.google.com/document/d/1TJSKoqsElTjnAVKy-nFcARGHthwv18PFdt8pnuorxvw/edit
Ohh, yes I will update this one

2022-04-06 12:10 UTC, sacOO7 commented on unity/SETUP.md
> +- Download and install git binary from https://git-scm.com/downloads (ignore if already installed)
Yeah, I think I can add `Skip` if already done .. maybe

2022-04-06 12:11 UTC, sacOO7 commented on unity/SETUP.md
> +- Unity projects are visible as a part of Unity Hub (list should be empty for none active projects)
`none` here means all of them are inactive, I couldn't find right word for it. I think `non active` or `inactive` refers to one specific project

2022-04-06 12:11 UTC, sacOO7 commented on unity/SETUP.md
> +- Select most recent LTS version and click on next to install the selected unity version.
Okay, I will check !

2022-04-07 05:13 UTC, sacOO7 commented on unity/README.md
> +- Make sure to [disable assembly validation](SETUP.md#disable-assembly-validation-error) if it fails due to conflict with internal newtonsoft json library.
We have provided link to **SETUP.md#disable-assembly-validation-error**. It mentions a detailed cause for the error.

2022-04-07 05:17 UTC, sacOO7 commented on unity/README.md
> +- Ably unity project supports both Mono and IL2CPP builds.
Updated!

2022-04-07 05:18 UTC, sacOO7 commented on unity/README.md
> +- NewtonSoft JSON DLL's can be removed, in case use of inbuilt Newtonsoft is preferred https://docs.unity3d.com/Packages/com.unity.nuget.newtonsoft-json@2.0/manual/index.html.
Updated!

2022-04-07 05:18 UTC, sacOO7 commented on unity/SETUP.md
> +4. Basics of unity [Official Unity Manual](https://docs.unity3d.com/Manual/index.html) and [Unity Beginner Manual](https://docs.google.com/document/d/1TJSKoqsElTjnAVKy-nFcARGHthwv18PFdt8pnuorxvw/edit
Done

2022-04-07 05:18 UTC, sacOO7 commented on unity/SETUP.md
> +- Download and install git binary from https://git-scm.com/downloads (ignore if already installed)
Done

2022-04-07 05:18 UTC, sacOO7 commented on unity/SETUP.md
> +- Select most recent LTS version and click on next to install the selected unity version.
Done

2022-04-07 05:18 UTC, sacOO7 commented on unity/SETUP.md
> +- All the tests should be available and shown under `EditMode.dll`
Done

2022-04-07 05:18 UTC, sacOO7 commented on unity/SETUP.md
> +- All the tests should be available and shown under `PlayMode.dll`
Done

2022-06-09 10:44 UTC, tomkirbygreen commented
Spoken with @sacOO7 before closing this. As we're taking a different approach, integrating Unity's Cloud Build with our GitHub build we'll be substantially rewriting this.

2022-06-09 10:44 UTC, closed without merging