Update documentation URLs
ably/ably-dotnet pull request #1149
Opened 2022-04-29 10:51 UTC by tomkirbygreen

Updatre any documentation URLs in the Markdown Files from `ably.com/documentation` to `ably.com/docs`.

2022-04-29 11:00 UTC, AndyNicks approved these changes

2022-05-03 09:48 UTC, owenpearson requested changes
I've grepped the codebase for `/documentation` and there's still a few culprits remaining in XML documentation tags that need editing.

2022-05-03 16:25 UTC, AndyNicks approved these changes

2022-05-04 08:49 UTC, QuintinWillison approved these changes

2022-05-04 09:48 UTC, owenpearson approved these changes
LGTM 👍

2022-05-04 14:44 UTC, merged