Feature/agent header
ably/ably-dotnet pull request #1195
Opened 2022-12-28 14:34 UTC by sacOO7

- Added basic ably agent header.
- Added test to check for agent header

2023-01-03 12:24 UTC, owenpearson requested changes

2023-01-03 12:24 UTC, owenpearson commented on src/IO.Ably.Shared/Defaults.cs
> +            var agentHeaders = $"{AblySdkIdentifier}";
This variable name seems misleading, if it's a set of headers it should be a `Dictionary<string, string>` but in this case it's just a `string` so I think you should call it `agentIdentifier` (as it's called in RSC7d)

2023-01-03 12:24 UTC, owenpearson commented on src/IO.Ably.Shared/Defaults.cs
> +                agentHeaders += $" {ablyDotnetRuntimeIdentifier}";
This logic seems kinda overcomplicated, would it not be simpler to collect the agents into a `String[]` and just return `String.join(" ", agents)`?

2023-01-04 05:48 UTC, sacOO7 commented on src/IO.Ably.Shared/Defaults.cs
> +                agentHeaders += $" {ablyDotnetRuntimeIdentifier}";
It's not complicated, it's a widely used syntax in dotnet. 
It's called `string interpolation` https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

2023-01-04 05:53 UTC, sacOO7 commented on src/IO.Ably.Shared/Defaults.cs
> +                agentHeaders += $" {ablyDotnetRuntimeIdentifier}";
You can see recommended ways to concatenate strings - https://learn.microsoft.com/en-us/dotnet/csharp/how-to/concatenate-multiple-strings.
`string.join` / `string.concat` needs collection/list to operate on.

2023-01-04 06:18 UTC, sacOO7 commented on src/IO.Ably.Shared/Defaults.cs
> +            var agentHeaders = $"{AblySdkIdentifier}";
Fixed!

2023-01-04 14:32 UTC, sacOO7 commented on src/IO.Ably.Shared/Defaults.cs
> +                agentHeaders += $" {ablyDotnetRuntimeIdentifier}";
done!

2023-01-04 16:07 UTC, owenpearson commented on src/IO.Ably.Shared/Defaults.cs
> +                agentHeaders += $" {ablyDotnetRuntimeIdentifier}";
nice, thanks! the tests are failing now because it expects the agents to be in a specific order, but once they're passing i'll approve 👍

2023-01-05 06:47 UTC, sacOO7 commented on src/IO.Ably.Shared/Defaults.cs
> +                agentHeaders += $" {ablyDotnetRuntimeIdentifier}";
Okay, fixed as a part of https://github.com/ably/ably-dotnet/pull/1195/commits/b40d7454ee3f6552f8d8f7eb62c27787c8ca99f1. I was passing `AblySdkIdentifier` instead of `product` value, so tests were failing

2023-01-05 11:55 UTC, owenpearson approved these changes
LGTM, thanks

2023-01-12 12:38 UTC, sacOO7 commented
Merging the PR since it's approved by @owenpearson : )

2023-01-12 12:38 UTC, merged