Fix authCallback token string
ably/ably-dotnet pull request #1197
Opened 2023-01-02 06:38 UTC by sacOO7

- Fixes #1196

2023-01-11 06:50 UTC, sacOO7 commented
@owenpearson I will be marking the old interface that returns `string` for `CreateTokenRequestAsync` and `CreateTokenRequest` as deprecated. We need to discuss if this should be made as breaking change or not, since the method signature is totally wrong as per spec -> https://sdk.ably.com/builds/ably/specification/main/features/#RSA9a

2023-01-12 21:24 UTC, sacOO7 commented
Updated as per discussion, maintained public methods.

2023-01-16 11:26 UTC, owenpearson requested changes
Looks good, just a couple of minor comments

2023-01-16 11:26 UTC, owenpearson commented on src/IO.Ably.Shared/AblyAuth.cs
> +        [Obsolete("This method will be removed in the future, please replace with a call to CreateTokenRequestObjectAsync")]
```suggestion
        [Obsolete("This method will be removed in a future version, please use CreateTokenRequestObjectAsync instead")]
```

2023-01-16 11:26 UTC, owenpearson commented on src/IO.Ably.Tests.Shared/Infrastructure/TaskCompleterAwaiterTests.cs
> +            await Task.Delay(1100);
what's the reason for this change?

2023-01-16 13:31 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Infrastructure/TaskCompleterAwaiterTests.cs
> +            await Task.Delay(1100);
Actually, the test was failing saying `timeoutExpired` as `false`.

2023-01-16 13:39 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Infrastructure/TaskCompleterAwaiterTests.cs
> +            await Task.Delay(1100);
I should be reverting the change since it doesn't really fix the issue lol. Maybe it was a sandbox issue.

2023-01-16 15:26 UTC, sacOO7 commented on src/IO.Ably.Shared/AblyAuth.cs
> +        [Obsolete("This method will be removed in the future, please replace with a call to CreateTokenRequestObjectAsync")]
updated!

2023-01-16 15:27 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Infrastructure/TaskCompleterAwaiterTests.cs
> +            await Task.Delay(1100);
removed the change!

2023-01-16 15:52 UTC, owenpearson commented on src/IO.Ably.Shared/AblyAuth.cs
> +        [Obsolete("This method will be removed in the future, please replace with a call to CreateTokenRequestObjectAsync")]
thanks!

2023-01-16 15:52 UTC, owenpearson approved these changes
LGTM. thanks

2023-01-18 14:24 UTC, sacOO7 commented
Thanks for approval 👍

2023-01-18 14:24 UTC, merged