Release/1.2.10
ably/ably-dotnet pull request #1201
Opened 2023-01-23 11:13 UTC by sacOO7

- Includes support for ably agent headers.
- Includes authCallback fix for accepting TokenRequest Object/ string token.
- Referred to https://github.com/ably/ably-dotnet/pull/1180

2023-01-25 16:03 UTC, owenpearson requested changes
Looks generally fine overall, but I don't know what `dotnet fake` does and I don't know about the unity release process so no opinion on that stuff

2023-01-25 16:03 UTC, owenpearson commented on CHANGELOG.md
> +- AuthCallback returned a string which can't be converted to TokenRequest [\#1196](https://github.com/ably/ably-dotnet/issues/1196)
I think we can tidy up the changelog entry a bit here:
- "Errors while creating transport!" should probably not have an exclamation mark
- Stuff like "Validate against 1.0 specification", "Create feature compliance manifest" etc. aren't customer facing so we should remove them.
- Ably-Agent header isn't really an enhancement

2023-01-25 17:08 UTC, sacOO7 commented on CHANGELOG.md
> +- AuthCallback returned a string which can't be converted to TokenRequest [\#1196](https://github.com/ably/ably-dotnet/issues/1196)
Errors while creating transport! is actually the name of the issue! So changelog captured it as is!

2023-01-26 11:05 UTC, QuintinWillison commented on CHANGELOG.md
> +- AuthCallback returned a string which can't be converted to TokenRequest [\#1196](https://github.com/ably/ably-dotnet/issues/1196)
What I often do is go back to the issue and also modify the title there. Nothing wrong with that. This is a good point to do that kind of housekeeping.

2023-01-26 11:13 UTC, QuintinWillison submitted a review, later dismissed
As far as I can see there are "closed issues" in this log which relate to things that are not in the `main` branch yet (that can be seen from correlating with the merged pull requests list). This is a limitation of the Github changelog generator tool we use, so requires manual intervention to remove them. I think this list should be a lot shorter for it to represent what users are actually getting for new in this SDK release.

Also, while we're here, perhaps worth updating `COPYRIGHT` given this is the first release we're doing in 2023. 😁

2023-01-26 11:13 UTC, QuintinWillison commented on CHANGELOG.md
> +- Override the default Dependabot configuration for NuGet [\#1188](https://github.com/ably/ably-dotnet/pull/1188) ([QuintinWillison](https://github.com/QuintinWillison))
The work done in this PR carries no value for users of the SDK, so I would remove this entry entirely.

2023-01-26 13:39 UTC, sacOO7 commented on CHANGELOG.md
> +- Override the default Dependabot configuration for NuGet [\#1188](https://github.com/ably/ably-dotnet/pull/1188) ([QuintinWillison](https://github.com/QuintinWillison))
Updated!

2023-01-26 14:07 UTC, owenpearson approved these changes
LGTM, thanks

2023-01-27 19:27 UTC, sacOO7 commented
Merging the PR since it's been approved : )

2023-01-28 07:29 UTC, merged