Fix build and package for IO.Ably.PackagePush.sln
ably/ably-dotnet pull request #1203
Opened 2023-01-27 20:07 UTC by sacOO7

- Fixes #1202

2023-02-07 11:39 UTC, marto83 approved these changes

2023-02-07 15:57 UTC, owenpearson requested changes

2023-02-07 15:57 UTC, owenpearson commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
Not sure if i'm comfortable with depending on something you're vendoring from your personal github, sorry. Could we put this in ably-forks?

2023-02-07 15:57 UTC, owenpearson commented on CONTRIBUTING.md
> +7. Go to [Github Actions tab](https://github.com/ably/ably-dotnet/actions), click on [Package Ably](https://github.com/ably/ably-dotnet/actions/workflows/package.yml) workflow at the left nav-bar. On
```suggestion
7. Go to [Github Actions tab](https://github.com/ably/ably-dotnet/actions), click on [Package Ably](https://github.com/ably/ably-dotnet/actions/workflows/package.yml) workflow at the left nav-bar. On the right corner, click on `Run workflow` with the current release tag as the input to `Ably version`.
```

2023-02-07 15:57 UTC, owenpearson commented on CONTRIBUTING.md
> +  - You can check all latest workflows under [Github Actions Tab](https://github.com/ably/ably-dotnet/actions). Donwload the generated artifact named `save-nuget-package` at the end of the latest suc
```suggestion
  - You can check all latest workflows under [Github Actions Tab](https://github.com/ably/ably-dotnet/actions). Download the generated artifact named `save-nuget-package` at the end of the latest successful workflow run.
```

2023-02-07 18:23 UTC, sacOO7 commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
We can, no issues with that. Please fork it into `ably-forks`.

2023-02-08 11:42 UTC, owenpearson commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
OK cool, i've created https://github.com/ably-labs/unity-packager and given you access. I actually think you should be using `actions/checkout` for this too btw. Also if you want to version it you should be using tags rather than branches.

2023-02-08 18:56 UTC, sacOO7 commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
Actually, I am skeptical about creating tags since it's easy to just switch to the branch and look at the relevant documentation. 
Also, branch `v2` is actually lot of commits behind `master` branch.

2023-02-09 20:41 UTC, owenpearson commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
It's easy to switch to the tag too? I think the main problem with branches is that you can push commits to them and then this workflow will immediately start using them

2023-02-09 20:41 UTC, owenpearson commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
The HEAD commit from `v1` is also a commit on the `master` branch so it should be easy to just add a tag to it

2023-02-09 20:42 UTC, owenpearson commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
Also I just realised I accidentally forked it to ably-labs instead of ably-forks whoops, I'll fix that now

2023-02-09 20:44 UTC, sacOO7 commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
Okay, great! Once you fork it to right repo. I will create tag there 👍

2023-02-09 20:46 UTC, owenpearson commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
OK I've created ably-forks/unity-packager and added the v1.0.0 tag. You should be able to do it like this now:
```yaml
- name: Checkout unity-packager repo
  uses: actions/checkout@v3
  with:
    repository: ably-forks/unity-packager
    ref: v1.0.0
    path: unity-packager

```

2023-02-09 20:56 UTC, sacOO7 commented on .github/workflows/package.yml
> +            git clone -b v1 https://github.com/sac-fork/unity-packager
done!

2023-02-09 20:58 UTC, owenpearson approved these changes
LGTM, thanks!

2023-02-09 21:24 UTC, merged