Update README
ably/ably-dotnet pull request #1207
Opened 2023-02-11 06:42 UTC by sacOO7

2023-02-16 14:01 UTC, tomczoink requested changes
Technically the recommended steps seem to work for me, just a few grammatical and formatting changes I think might help.

2023-02-16 14:01 UTC, tomczoink commented on unity/README.md
> +- Please take a look at [contributing doc](CONTRIBUTING.md) for information related to local dev-setup, writing and running tests.
```suggestion
- Please take a look at the [contributing documentation](CONTRIBUTING.md) for information relating to local development setup, and writing and running tests.
```

2023-02-16 14:01 UTC, tomczoink commented on unity/README.md
> +- Detailed information related to updating ably DLLs using [unity plug-ins](https://docs.unity3d.com/Manual/Plugins.html) is given at [updating-ably-unitypackage](CONTRIBUTING.md#updating-ably-unityp
```suggestion
- Detailed information related to updating Ably DLLs using [Unity Plugins](https://docs.unity3d.com/Manual/Plugins.html) is available in [updating-ably-unitypackage](CONTRIBUTING.md#updating-ably-unitypackage).
```

2023-02-16 22:21 UTC, sacOO7 commented on unity/README.md
> +- Please set `ClientOptions.AutomaticNetworkStateMonitoring` to `false` in the code, since the feature is not supported and throws runtime exception.
We are planning to fix it here https://github.com/ably/ably-dotnet/issues/1212

2023-03-02 14:03 UTC, tomczoink approved these changes
LGTM

2023-03-03 19:51 UTC, merged