Fix QueueMessages when set to false
ably/ably-dotnet pull request #1216
Opened 2023-03-21 15:13 UTC by sacOO7

2023-04-01 18:31 UTC, sacOO7 commented
Tests need to be added to fix the issue properly

2023-04-30 17:47 UTC, sacOO7 commented
It seems test can be updated for `send` using `TestTransportFactory`

2023-04-30 17:51 UTC, sacOO7 commented
Need to mock send response, failing the message and then checking the failed message doesn't get added to the queue.

2023-05-15 15:10 UTC, owenpearson requested changes

2023-05-15 15:10 UTC, owenpearson commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                public async Task ChannelStateCondition_WhenQueueMessagesIsFalse_ShouldntQueueMessages_WhenSendFails(Protocol protocol)
I don't think this is actually testing for the correct behaviour of `ClientOptions.QueueMessages`.

The way I would suggest testing it is:
1. Create a realtime client with `QueueMessages = false`
2. Force the client into the `DISCONNECTED` state.
3. Assert that calling `RealtimeChannel.Publish` (or `PublishAsync`) results in an exception
4. Assert that the message queue is empty

It might be worth also having another test that checks the behaviour when `QueueMessages` is true":
1. Create a realtime client with `QueueMessages = true`
2. Force the client into the `DISCONNECTED` state.
3. Call `RealtimeChannel.Publish` (or `PublishAsync`)
4. Assert that the message is in the message queue
5. Force the client back into the `CONNECTED` state
6. Assert that the message has now been published

2023-05-15 15:19 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                public async Task ChannelStateCondition_WhenQueueMessagesIsFalse_ShouldntQueueMessages_WhenSendFails(Protocol protocol)
We already have test for both cases
For first case -
https://github.com/ably/ably-dotnet/blob/4d780978f4aff702b9ab0404bdc78591f518a65a/src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs#L1629

For second case -
https://github.com/ably/ably-dotnet/blob/4d780978f4aff702b9ab0404bdc78591f518a65a/src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs#L1668

Currently, we are adding a test for a really special case where if send fails, it should check if `QueueMessages` is false, accordingly it should handle message queuing.

2023-05-15 15:21 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                public async Task ChannelStateCondition_WhenQueueMessagesIsFalse_ShouldntQueueMessages_WhenSendFails(Protocol protocol)
I think it was missing before, that's why we had a issue where sometimes, messages were being queued.

2023-05-15 18:41 UTC, SimonWoolf reviewed
Couple comments, overall looks plausible to me but I'll leave it to Owen to approve when he's happy

2023-05-15 18:41 UTC, SimonWoolf commented on src/IO.Ably.Shared/Transport/ConnectionManager.cs
> +                        HttpStatusCode.ServiceUnavailable);
503 is the code for a serverside issue, not appropriate for client disconnected. 400 isn't perfect but better

2023-05-15 18:41 UTC, SimonWoolf commented on src/IO.Ably.Shared/Transport/ConnectionManager.cs
> +                    throw new AblyException($"The current state [{State.State}] does not allow messages to be sent.");
Shouldn't this have a Code and StatusCode?

2023-05-18 15:55 UTC, sacOO7 commented on src/IO.Ably.Shared/Transport/ConnectionManager.cs
> +                    throw new AblyException($"The current state [{State.State}] does not allow messages to be sent.");
updated

2023-05-18 15:56 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
> +                public async Task ChannelStateCondition_WhenQueueMessagesIsFalse_ShouldntQueueMessages_WhenSendFails(Protocol protocol)
I think we have feature spec updated as a part of https://github.com/ably/specification/issues/134

2023-05-22 10:04 UTC, owenpearson approved these changes
LGTM, thanks

2023-05-22 10:05 UTC, owenpearson approved these changes
LGTM, thanks

2023-05-22 10:26 UTC, sacOO7 commented
Thanks for the approval, merging the PR : )

2023-05-22 10:26 UTC, merged