Updated connectionTtl to be 120 seconds
ably/ably-dotnet pull request #1247
Opened 2023-06-30 16:43 UTC by sacOO7

- Fixed #1243

2023-07-06 09:45 UTC, owenpearson requested changes

2023-07-06 09:45 UTC, owenpearson commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
> +            client.Connection.ConnectionStateTtl.Should().Be(Defaults.ConnectionStateTtl);
This test change isn't quite right - what this test does is ensure that once a client is connected, the `Connection.ConnectionStateTtl` field is populated with the `connectionStateTtl` from connection details. I'm not sure how easy this is to do with dotnet tests, but to test this properly you need to change the value of `Defaults.ConnectionStateTtl` and assert that the value of `Connection.ConnectionStateTtl` changes when you become connected (as the test was doing before).

2023-07-06 11:12 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
> +            client.Connection.ConnectionStateTtl.Should().Be(Defaults.ConnectionStateTtl);
Then this test should be removed wdyt? I think currently we are just checking if test doesn't fail.

2023-07-06 12:41 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
> +            client.Connection.ConnectionStateTtl.Should().Be(Defaults.ConnectionStateTtl);
Also. we haven't marked the test with any spec id yet.

2023-07-06 14:37 UTC, owenpearson commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
> +            client.Connection.ConnectionStateTtl.Should().Be(Defaults.ConnectionStateTtl);
I don't think we should remove the test, the behaviour is defined by [`DF1a`](https://sdk.ably.com/builds/ably/specification/main/features/#DF1a).

If we don't test this and someone breaks it then we could end up in a situation where we change the server-side `connectionStateTtl` but ably-dotnet clients just ignore the new value, therefore it's important to test that the `connectionStateTtl` from connection details is used

2023-07-07 17:59 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
> +            client.Connection.ConnectionStateTtl.Should().Be(Defaults.ConnectionStateTtl);
Updated test as per suggestion.

2023-07-10 13:53 UTC, merged