Fix Property Typo
ably/ably-dotnet pull request #432
Opened 2020-08-01 14:52 UTC by sacOO7

- Renamed LogHander property to LogHandler in ClientOptions.
- Refactored the change in relevant property references.
- Fixes #427.

2020-08-19 09:23 UTC, QuintinWillison requested changes
The old interface should be deprecated, not removed, per my commentary in #427. Thanks.

2020-08-19 21:11 UTC, sacOO7 commented
Hi @QuintinWillison , I have marked current properly as deprecated. Compiler will show warning if it's used anywhere in the code. (We can make it to show as error if required). I am not sure if we need to introduce new property ```LogHandler``` as a part of this PR.

2020-08-20 07:19 UTC, QuintinWillison commented
Yes, the introduction of the new property is essential for this fix!

What I was pointing out is that simultaneously the deprecation needs to be introduced. Thus, overall, the fix is atomic in that new users of this API can use the correct name and those with existing codebases will not completely break as they will get a deprecation warning.

2020-08-20 07:20 UTC, QuintinWillison requested changes
As stated above this PR also needs to include the new property interface and implementation. The deprecated property implementation should internally delegate to the new implementation.

2020-08-20 07:20 UTC, QuintinWillison commented on src/IO.Ably.Shared/ClientOptions.cs
> +        [ObsoleteAttribute("This property is obsolete/deprecated", false)]
The deprecation message has to point the user to the property name they should be using, please.

2020-08-20 20:26 UTC, QuintinWillison requested changes
Thanks for adding tests but that has opened up another couple of small queries from me. 😁

2020-08-20 20:26 UTC, QuintinWillison commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +        public void Options_WithLogHanderReturns_LogHandlerWithSameLoggerSink()
I'm not sure what the naming convention here is but wouldn't this be more logical?
```suggestion
        public void Options_WithLogHander_ReturnsLogHandlerWithSameLoggerSink()
```

2020-08-20 20:26 UTC, QuintinWillison commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +            Assert.Same(options.LogHander, testLoggerSink);
This feels over the top in terms of validation. Wouldn't `Assert.Equal` achieve what you really need to check? I'm assuming the `LogHandler` property is not designed to copy the provided instance, therefore a simple check of the reference should suffice and makes less assumptions about the implementation of the object instances being verified?

2020-08-20 20:32 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +        public void Options_WithLogHanderReturns_LogHandlerWithSameLoggerSink()
Sure, I guess I was referring to the test naming convention from https://github.com/ably/ably-dotnet/blob/344d1d2741daee45ca37b411c07cfc35c4e88a8b/src/IO.Ably.Tests.Shared/ApiKeyTests.cs#L17.
But surely, makes sense to change it to the above name.

2020-08-20 20:36 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +            Assert.Same(options.LogHander, testLoggerSink);
I think equal checks if two objects are equal, Assert.Same checks if they belong to the same instance.

2020-08-20 20:40 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +            Assert.Same(options.LogHander, testLoggerSink);
I think Assert.Equal method can have typical checks for instance check (uses overridden equals method internally), hashcode check and may check for internal data. Assert.Same is more simple IMO.

2020-08-20 20:43 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +            Assert.Same(options.LogHander, testLoggerSink);
You can say, ```Assert.Same``` checks if references are the same.

2020-08-20 20:55 UTC, QuintinWillison commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +            Assert.Same(options.LogHander, testLoggerSink);
Yup, I was wrong. Sorry. Read an incorrect blog post somewhere. 🤦

2020-08-20 20:57 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
> +            Assert.Same(options.LogHander, testLoggerSink);
Yeah no worries : )

2020-09-24 10:25 UTC, merged