[WIP] Fix auth token clock-skew
ably/ably-dotnet pull request #439
Opened 2020-09-21 08:32 UTC by sacOO7

- Removed token expiry check from auth flow
- Fixes #303

2020-09-22 18:22 UTC, sacOO7 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ServerNow = () => Now() - diff;
Can we move the definition for this at class level, we can store the diff in a variable that can be accessed from there.

2020-09-23 09:47 UTC, marto83 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ServerNow = () => Now() - diff;
We can but I don't see any benefit at the moment. We can do it when we implement the check whether the local time has drifted.

2020-09-23 09:48 UTC, marto83 commented
I updated the PR implementing RSA4b1 so we only check the expiry of the time if we have server time and the token has an expiry field. I had to fix some tests on the way because they were expecting the check to happen automatically.

2020-09-23 09:51 UTC, sacOO7 commented
Its easy to understand that way. I think the confusion was caused because
of ServerNow implementation. I thought it's a class variable. Tbh, I am new
to this kind of pattern ( where global class fun. definition is dynamically
set in a local function )

On Wed, Sep 23, 2020, 15:17 Martin Georgiev <notifications@github.com>
wrote:

> *@marto83* commented on this pull request.
> ------------------------------
>
> In src/IO.Ably.Shared/AblyAuth.cs
> <https://github.com/ably/ably-dotnet/pull/439#discussion_r493384821>:
>
> > -            ServerTimeOffset = () => Now() - diff;
> +            var serverTime = await ServerTime();
> +            if (Logger.IsDebug)
> +            {
> +                Logger.Debug("Received server time: " + serverTime);
> +            }
> +
> +            TimeSpan diff = Now() - serverTime;
> +
> +            if (Logger.IsDebug)
> +            {
> +                Logger.Debug("Server time differs from device Now by: " + diff);
> +            }
> +
> +            // TODO: Save servertime and check if now has drastically changed
> +            ServerNow = () => Now() - diff;
>
> We can but I don't see any benefit at the moment. We can do it when we
> implement the check whether the local time has drifted.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ably/ably-dotnet/pull/439#discussion_r493384821>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD7S6SM2NMNG3DUFJ2RAPELSHG73VANCNFSM4RUICMCQ>
> .
>

2020-09-23 10:05 UTC, QuintinWillison requested changes
It's difficult to review this change at a high level because there's a lot going on and I don't have enough knowledge of the inner workings of this library to assess impact, therefore have to trust you in terms of general architectural fit.

Hence, my comments are more smaller nit picks. Sorry!

2020-09-23 10:05 UTC, QuintinWillison commented on src/IO.Ably.Shared/TokenDetails.cs
> +            Expires = now.AddDays(-1);
This feels a little bit arbitrarily 'magic'. Would it not be safer to have a discrete boolean field to indicate explicitly expired? This mutation is effectively meaningless and could actually be misleading in some circumstances.

2020-09-23 10:05 UTC, QuintinWillison commented on src/IO.Ably.Shared/TokenDetails.cs
> +            return token.IsExpired(serverTime.Value) == false;
Not sure why the explicit `== false` here, as I've commented on elsewhere. Why not?:

```suggestion
            return !token.IsExpired(serverTime.Value);
```

2020-09-23 10:25 UTC, marto83 commented on src/IO.Ably.Shared/AblyAuth.cs
> +                if (HasServerTime == false && Options.QueryTime == true)
😂 I love boolean logic discussions. 
for `Options.QueryTime` I have to explicitly compare to `true` because it is nullable and it complains if you just leave it. 
For `!HasServerTime` vs `HasServerTime == false` it's just a personal preference because it makes it easier to see. I don't mind changing it if there is a convention in Ably otherwise I'd prefer to leave it `== false`

2020-09-23 10:32 UTC, QuintinWillison commented on src/IO.Ably.Shared/AblyAuth.cs
> +                if (HasServerTime == false && Options.QueryTime == true)
Understood if coercion involved, but when comparing fields where the assigned type is boolean then no need.

2020-09-23 10:34 UTC, marto83 commented on src/IO.Ably.Shared/TokenDetails.cs
> +            Expires = now.AddDays(-1);
Agree. I was not really fixing that function but just needed to be able to pass the date. I'll check where it is used and whether I can remove it.

2020-09-23 13:58 UTC, marto83 commented on src/IO.Ably.Shared/TokenDetails.cs
> +            Expires = now.AddDays(-1);
I've removed the method completely. It was only used internally.

2020-09-23 14:59 UTC, sacOO7 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ServerNow = () => Now() - diff;
Its easy to understand that way. I think the confusion was caused because
of ServerNow implementation. I thought it's a class variable. Tbh, I am new
to this kind of pattern ( where global class fun. definition is dynamically
set in a local function )

2020-09-23 19:09 UTC, sacOO7 commented
@marto83 I took a pull and try running the tests, seens ```RealTimeWithAuthUrl_WhenTokenExpired_ShouldRetry_WhenRetryFails_ShouldSetError``` and 
```Auth_WithRealtimeClient_WhenAuthFails_ShouldTransitionToOrRemainInTheCorrectState``` is failing

I was able to make the first one work after increasing the awaiter timeout. Not sure about the second one.

2020-09-24 09:14 UTC, marto83 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ServerNow = () => Now() - diff;
no problem. For sure, it's not the most obvious way of doing it and it could be done much better. Could you please add a issue about it.

2020-09-24 09:17 UTC, marto83 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            // TODO: Save servertime and check if now has drastically changed
Create issue #441 441

2020-09-24 09:21 UTC, marto83 approved these changes
Looks good

2020-09-24 09:26 UTC, marto83 commented
@sacOO7 regarding your message about failing tests. I've created another branch to look at all the test separately and make sure our current CI builds pass before making the next release.

2020-09-24 09:26 UTC, QuintinWillison commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ServerNow = () => Now() - diff;
@sacOO7 we're going to get this PR merged but I would appreciate it if you could please resolve this conversation once you are happy and/or have created this issue. Thanks.

2020-09-24 09:27 UTC, QuintinWillison approved these changes

2020-09-24 09:47 UTC, sacOO7 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ServerNow = () => Now() - diff;
will fix as a part of https://github.com/ably/ably-dotnet/issues/441 as per conversation

2020-09-24 10:26 UTC, merged