Feature/452 transport params
ably/ably-dotnet pull request #453
Opened 2020-10-15 22:32 UTC by marto83

Spec align. Add custom Transport params dictionary to ClientOptions

2020-10-19 13:04 UTC, QuintinWillison requested changes

2020-10-19 13:04 UTC, QuintinWillison commented on src/IO.Ably.Shared/ClientOptions.cs
> +        public Dictionary<string, string> TransportParams { get; set; } = new Dictionary<string, string>();
[RTC1f](https://docs.ably.io/client-lib-development-guide/features/#RTC1f) states that these values should simply be `Stringifiable` (spec. wording, not mine) so perhaps the values here should be `Object` and your implementation then uses [`ToString()`](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=netcore-3.1)?

2020-10-19 13:23 UTC, marto83 commented on src/IO.Ably.Shared/ClientOptions.cs
> +        public Dictionary<string, string> TransportParams { get; set; } = new Dictionary<string, string>();
I did see that but didn't think it added much value as these will be used for query parameters. I'm happy to change it and call `ToString()` if you think it's required.

2020-10-19 13:51 UTC, sacOO7 commented on src/IO.Ably.Shared/ClientOptions.cs
> +        public Dictionary<string, string> TransportParams { get; set; } = new Dictionary<string, string>();
I agree with @QuintinWillison [RTC1f](https://docs.ably.io/client-lib-development-guide/features/#RTC1f), it states If values are unidiomatic to the language, the implementer may consider this as equivalent to String. Since dotnet is a typed language, it will be great if we can leverage that feature and be specific with values stored in the map. I am not sure if the current implementation works without being specific with values, I am considering usability wrt passed values in ClientOptions.

2020-10-19 14:05 UTC, sacOO7 commented on src/IO.Ably.Shared/ClientOptions.cs
> +        public Dictionary<string, string> TransportParams { get; set; } = new Dictionary<string, string>();
Maybe use something like ```where T : struct, string``` for value

2020-10-19 14:13 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
> +            Assert.True(true);
😵😱

2020-10-19 14:20 UTC, sacOO7 commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            if (AdditionalParameters?.Any() ?? false)
Any returns a bool value, can we remove ```?? false``

2020-10-19 14:28 UTC, sacOO7 commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            if (AdditionalParameters?.Any() ?? false)
Can we make it more simple to read
```if ( param is not null && param.any)```
Took me some time to understand why ```false``` was needed

2020-10-21 10:18 UTC, marto83 commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
> +            Assert.True(true);
The test just makes sure `GetUri()` doesn't throw an exception.

2020-10-21 10:30 UTC, sacOO7 commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
> +            Assert.True(true);
Can we use ```RecordException``` to be explicit about assertions 
https://github.com/xunit/xunit/blob/master/test/test.xunit.assert/Asserts/RecordTests.cs

2020-10-21 14:20 UTC, marto83 commented on src/IO.Ably.Shared/ClientOptions.cs
> +        public Dictionary<string, string> TransportParams { get; set; } = new Dictionary<string, string>();
@QuintinWillison I've updated the params to accept `object` for the values. 
@sacOO7 as it's not a very mainstream feature I'm going to keep it simple. :)

2020-10-21 14:22 UTC, marto83 commented on src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
> +            Assert.True(true);
Thanks Sachin. Great suggestion. I updated the code.

2020-10-21 14:28 UTC, marto83 commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            if (AdditionalParameters?.Any() ?? false)
I haven't upgraded to c# 9 yet. Once we switch we can use `is not null`. Currently it is not available.

2020-10-21 14:33 UTC, sacOO7 commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            if (AdditionalParameters?.Any() ?? false)
what about ``` ( param != null ) ``` 😉

2020-10-21 14:41 UTC, marto83 commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            if (AdditionalParameters?.Any() ?? false)
I think we fall in the lang of personal preference 😁

2020-10-21 14:46 UTC, sacOO7 commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            if (AdditionalParameters?.Any() ?? false)
Yeah, but tbh, this syntax ( sugar ) is new to me : )

2020-10-21 14:47 UTC, sacOO7 commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            if (AdditionalParameters?.Any() ?? false)
See, if you can change it, I am just looking at it from a readability perspective

2020-10-21 14:49 UTC, sacOO7 approved these changes

2020-10-26 11:22 UTC, QuintinWillison approved these changes

2020-10-26 11:22 UTC, QuintinWillison commented on src/IO.Ably.Shared/Transport/TransportParams.cs
> +            Dictionary<string, string> StringifyParameters(Dictionary<string, object> originalParams)
I'm not going to insist on it, however my preference would be to lean less on system tests to validate and instead put in place some unit tests specifically for methods like this. It's very unit testable, especially in respect of specific corner cases you had in mind (as is clearly the case looking at the implementation). Perhaps one to think more on for future.

2020-10-27 16:41 UTC, merged