Generate environment fallbacks
ably/ably-dotnet pull request #454
Opened 2020-10-19 19:47 UTC by sacOO7

- Refactored ClientOptions
- Added environment fallbacks method to Defaults

2020-10-21 13:57 UTC, sacOO7 commented
@marto83 I was going through the ClientOptions, I see a lot of refactoring scope as a part of fixing env. fallbacks
 1. ClientOption properties duplicated with accessor methods
- Following properties are directly accessible, although separate access methods are provided. I believe business logic can be moved inside the get accessor itself (otherwise need to remove get from the property)

2020-10-21 15:37 UTC, marto83 commented
@sacOO7. I had a look at some of the methods you mentions `GetClientId` ... they are quite handy and simplify some of the code. 

How are you thinking of simplifying / removing them?

2020-10-21 15:38 UTC, marto83 commented
So far the PR looks good. Where are you going to use the `GetEnvironmentFallbackHosts()` method?

2020-10-21 15:46 UTC, sacOO7 commented
> GetEnvironmentFallbackHosts

I will put the logic inside ```FallbackHosts { get { } }``` itself. I don't think we need to define it anywhere else.

2020-10-21 15:48 UTC, sacOO7 commented
> @sacOO7. I had a look at some of the methods you mentions `GetClientId` ... they are quite handy and simplify some of the code.
> 
> How are you thinking of simplifying / removing them?

I will create the PR itself, then it will be more clear and you can suggest me changes, if any : )

2020-10-22 20:15 UTC, sacOO7 commented
> @sacOO7. I had a look at some of the methods you mentions `GetClientId` ... they are quite handy and simplify some of the code.
> 
> How are you thinking of simplifying / removing them?

@marto83 you can take a look at implementation and let me know about your thoughts : )

2020-10-26 22:26 UTC, lmars approved these changes
I'm unfamiliar with .NET, but the logic looks good to me 👍

2020-11-14 00:58 UTC, marto83 commented
The logic is ok. 
By convention in this project I don't put much logic in .net properties. Properties should have simple getters and setting with a minimum amount of logic. 
Can you convert the Properties you refactored and also can you create a method for Fallback hosts and call that. This way we can continue with the 'Properties are simple' convention.

2020-11-16 07:03 UTC, sacOO7 commented
- I didn't see much complex logic in ```RestHost``` and ```RealtimeHost```. Just a few if-else conditions. 
- I can refactor ```FallbackHosts```. makes sense to move out the logic. Not sure if it can be kept internal and then routed through ```get``` ( instead of keeping ```get``` private)

2020-11-16 09:56 UTC, marto83 requested changes
It's not about the amount of code but the principle about keeping the properties very simple. It is much better to have the `ClientSettings` object plain so when you ask for the debug info you can get everything the client has set and not calculated properties. 
For example if the client hasn't entered fallback hosts you will get `null` but if they have you will get exactly what they have entered. If the property is calculated you will get some default hosts. Of course if you knew the logic you can figure it out. The point is to keep things obvious.
Can you please remove all logic from properties in Client

2020-11-16 17:12 UTC, sacOO7 commented
@marto83 I have updated the code, you can review it now

2020-11-16 17:16 UTC, sacOO7 commented on src/IO.Ably.Shared/ClientOptions.cs
> +        public string RestHost
I partially agree with you. But, we already have a property container which can be used for debugging the passed value. Using properties without any logic ( when we can),  kind of makes it look like any other publicly available variable.

2020-11-29 20:33 UTC, marto83 reviewed
Looks good. Thanks for reverting the changes. 
Can you just double check the Options.ClientId. I'm happy to approve once that is done.

2020-11-29 20:33 UTC, marto83 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ?? Options.ClientId;
I think you forgot to revert this change. 
Everything else looks good.

2020-11-29 20:36 UTC, sacOO7 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ?? Options.ClientId;
I have marked GetClientId() as obsolete. That's why I used ClientId here

2020-11-29 20:42 UTC, marto83 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ?? Options.ClientId;
GetClientId() is internal. No need to mark it as obsolete. Regardless could you turn `ClientId` back to a simple property and either user `GetClientId()` or even better remove it from ClientOptions and create a private helper methed inside AblyAuth that implements the logic :)

2020-11-29 20:53 UTC, sacOO7 commented on src/IO.Ably.Shared/AblyAuth.cs
> +            ?? Options.ClientId;
Okay

2020-11-30 10:12 UTC, marto83 approved these changes

2021-04-15 10:25 UTC, kavalerov commented
@QuintinWillison / @owenpearson  why is the linked issue close, but this PR is open - did we actually merge/implement this?

2021-04-19 07:42 UTC, QuintinWillison commented
The linked issue [has been re-opened](https://github.com/ably/ably-dotnet/issues/438#issuecomment-820315945).

2021-04-22 13:04 UTC, merged