Push/handle event
ably/ably-dotnet pull request #686
Opened 2021-07-26 09:09 UTC by marto83

2021-07-26 10:07 UTC, tomkirbygreen requested changes
My bad: clicked merge on the screaming-caps PR before I saw you comment. I'll be more careful in future. Would you be able to integrate the changes just this once?

I just have one comment about this PR.

2021-07-26 10:07 UTC, tomkirbygreen commented on src/IO.Ably.Shared/Push/ActivationStateMachine.cs
> +            var canEnter = await _handleEventsLock.WaitAsync(2000); // Arbitrary number = 2 second
I'm slightly concerned about the phrase `'Arbitrary number'` in source code that customers can see. Can we find some different words perhaps? Where does the magic 2 seconds come from?

2021-07-26 10:31 UTC, marto83 commented on src/IO.Ably.Shared/Push/ActivationStateMachine.cs
> +            var canEnter = await _handleEventsLock.WaitAsync(2000); // Arbitrary number = 2 second
I didn't want to make the wait indefinite but also didn't know how short it should be. 2 seconds worked ok in the initial integration testing but I haven't got to that part yet in the PR process. That's why I've put that for now it's arbitrary. Once we have done more real world testing and checked logs it will either prove that 2s works or we will have to tweak it.

2021-07-27 17:17 UTC, marto83 commented
@tomkirbygreen I've resolved the conflict :)

2021-07-28 14:22 UTC, tomkirbygreen approved these changes

2021-07-28 14:22 UTC, merged